config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  schema_data :jsonb
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  tenant_id   :bigint           not null
#
# Indexes
#
#  index_users_on_schema_data  (schema_data) USING gin
#  index_users_on_tenant_id    (tenant_id)
#
# Foreign Keys
#
#  fk_rails_...  (tenant_id => tenants.id)
#
class User < ApplicationRecord
  include SchemaAttributable

  belongs_to :tenant
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :convert_schema_data_types, only: %i[create update]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new(name: "New User", tenant_id: Tenant.first.id)
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to(users_path, notice: "User was successfully created.") }
        format.json { render(:show, status: :created, location: @user) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @user.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to(users_path, notice: "User was successfully updated.") }
        format.json { render(:show, status: :ok, location: @user) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @user.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to(users_url, notice: "User was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :tenant_id, schema_data: {})
  end

  def convert_schema_data_types
    schema_data = user_params[:schema_data].to_h
    return unless schema_data

    schema_data.each do |key, value|
      schema_data[key] = @user.convert_string_to_schema_value(key, value)
    end

    params[:user][:schema_data] = schema_data
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<% if user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка!</h4>
    <p><%= pluralize(user.errors.count, "error") %> запретили сохранение этого пользователя:</p>
    <hr>
    <ul>
      <% user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: user, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
  <% user.schema_attributes.each do |key| %>
    <div class="mb-3">
      <%= form.label key, class: 'form-label' %>
      <% case user.schema_attribute_type(key) %>
      <% when 'String' %>
        <%= form.text_field :schema_data, name: "user[schema_data][#{key}]", value: user.schema_data[key], class: 'form-control' %>
      <% when 'Integer' %>
        <%= form.number_field :schema_data, name: "user[schema_data][#{key}]", value: user.schema_data[key], class: 'form-control' %>
      <% when 'SingleSelect' %>
        <%= form.select :schema_data, options_for_select(user.schema_enum_values(key), selected: user.schema_data[key]), {}, {name: "user[schema_data][#{key}]", class: 'form-select'} %>
      <% when 'MultiSelect' %>
        <%= form.select :schema_data, options_for_select(user.schema_enum_values(key), selected: user.schema_data[key]), {}, {name: "user[schema_data][#{key}][]", multiple: true, class: 'form-select'} %>
      <% else %>
        <p class="text-muted">Unsupported field type</p>
      <% end %>
    </div>
  <% end %>

  <div class="text-center">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_short_form.erb
<%= form_with(model: user, html: { class: 'needs-validation', novalidate: '' }) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', required: '' %>
    <div class="invalid-feedback">
      <%= user.errors[:name].first %>
    </div>

    <%= form.label :tenant_id %>
    <%= form.select :tenant_id, Tenant.all.collect { |t| [t.id] }, class: 'form-control', required: '' %>
    <div class="invalid-feedback">
      <%= user.errors[:tenant_id].first %>
    </div>
  </div>

  <div class="text-center">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>Name: <%= user.name %></p>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Attribute</th>
          <th scope="col">Type</th>
          <th scope="col">Required?</th>
          <th scope="col">Value</th>
        </tr>
      </thead>
      <tbody>
        <% user.list_schema_attributes.each_with_index do |item, index| %>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <td><%= item.first %></td>
            <td><%= item.last %></td>
            <td><%= '✓' if user.schema_field_required?(item.first) %></td>
            <td><%= user.schema_data[item.first] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Edit this user", edit_user_path(user) %>
      <%= link_to "Destroy this user", user, method: :delete %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "short_form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>